### ISSUE TITLE
Synonym direkt zuweisen

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#10]
Nach dem Anlage neu erstellen sollte das entsprechende Synonym direkt zugewiesen werden. Dazu die Synonym-Id als Parameter übergeben?

**Comment by KTim21** [comment]
Ich verstehe noch nicht ganz, was da passieren soll.

**Comment by irenenirgendwo** [comment]
Naja, bei dem automatischen Einlesen kann mensch ja entweder eine Anlage zuordnen aus der Liste oder eine neu erzeugen. Wenn eine neu erzeugt wird, wäre es schön, wenn sie bei dem Button zu dem Synonym, von dem sie aus erzeugt wurde (Listenelement), nicht mehr zugeordnet werden muss, sondern gleich das Synonym zu der Anlage gespeichert wird.
