### ISSUE TITLE
Bei neuem Transport: Neue Anlage/Neuer Stoff

### ISSUE THREAD

**Issue by KTim21** [irenenirgendwo/urantransporte#24]
Beim Transport erstellen einen Button, um eine neue Anlage/einen neuen Stoff zu erzeugen.

**Comment by KTim21** [comment]
Die Modals sollten funktionieren. Datepicker kommt demnächst.

**Comment by irenenirgendwo** [comment]
Super. Denkst du auch an den Datepicker bei den Beobachtungen (Vergangenheit statt Zukunft auswählbar)
