### ISSUE TITLE
Rückmeldung zur Abfrageneinschränkung

### ISSUE THREAD

**Issue by Wurzelkoch** [irenenirgendwo/urantransporte#30]
Regelmäßig kann man Listen nach bestimmten Kriterien einschränken (z.B. Transporte nach Stoff, Beobachtungen nach Zuordnung, Anlagen in der Auflistung und der Abfragenseite nach Kategorie)
Es wäre wertvoll, wenn die gewählte Einschränkung nicht nur als Parameter in der Adresszeile des Browsers auftaucht, sondern über einen veränderten Text oder (edler) durch Hervorhebung der Auswahlfläche sichtbar wäre.

**Comment by KTim21** [comment]
Wo versteckt sich der noch nicht korrigierte Filter in „Abfragen“?

**Comment by irenenirgendwo** [comment]
Ich bin der Meinung da gibt es keinen richtigen Filter. Was vielleicht da verbessert werden könnte, ist die Anlagenauswahl über eine Anlagen-Suche-Möglichkeit oder ähnliches, aber ein Filter ist da soweit ich weiß nicht vorgesehen. Ist ja praktisch ein großer Filter.

**Comment by KTim21** [comment]
Ok, dann erlaube ich mir, den Issue zu schließen.
