### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#31]
Es wäre toll, wenn bei Änderungen auch die Tests so angepasst würden, dass sie immer noch lauffähig sind. (Wenn z.B. Spalten in Tabellen geändert werden müssen in test/fixtures die entsprechenden Testdatensätze angepasst werden.) 
Die automatisierten Tests sind gut zur Fehlersuche, deshalb nutze ich sie gerne, mag aber nicht immer erst alles neu anpassen müssen.

**Comment by KTim21** [comment]
Ich achte (neuerdings...) drauf.

**Comment by KTim21** [comment]
Wir achten jetzt hoffentlich alle in der Regel drauf, deswegen schließe ich den mal.
