### ISSUE TITLE
load_foto nicht automatisch bei Bearbeitung

### ISSUE THREAD

**Issue by Wurzelkoch** [irenenirgendwo/urantransporte#32]
Ich fänd es sinnig, wenn beim Bearbeiten einer Beobachtung die Eingabemaske zum Foto Hochladen explizit aufgerufen werden kann und nicht automatisch erscheint, wenn andere Daten bearbeitet wurden.

**Comment by irenenirgendwo** [comment]
Momentan ist die Anzeige-Seite nicht auf priviligierte Benutzer beschränkt, sondern wird nach dem Hochladen eines Fotos allen zur Verfügung gestellt, manchmal kommt dabei auch eine Error-Meldung. Konkreter Userflow soll im Integration-Test beschrieben werden, dann kann das automatisiert getestet werden.
