### ISSUE TITLE
Fehler bei Zeitverarbeitung

### ISSUE THREAD

**Issue by Wurzelkoch** [irenenirgendwo/urantransporte#33]
Nachdem ich eine (geratene) Umwandlung von Jahreszahlen wie 0001 (bei Eingabe dd.mm.yy oder yy/mm/dd) zu Jahreszahlen größer 1990 eingebaut habe, ist mir folgendes aufgefallen:
Wenn mensch bei der Eingabe einer Beobachtung die Zeit per Hand (ohne Kalender-addon) eingibt, werden z.B. alle folgenden Angaben zu 03.02.2001: 2001/2/3; 1/2/3; 1.2.3; 1.2.03.
Vor allem mit letzterer Eingabe sollten wir (auch wenn ein Hinweis auf Datumsformat eingebaut wird) unbedingt rechnen. Wie fängt man das ab, wenn rails bei Abwesenheit von vierstelligen Jahreszahlen immer das Schema yy/mm/dd bzw. yy.mm.dd annimmt?

**Comment by irenenirgendwo** [comment]
Insbesondere: Bei Beobachtungen müssen Datum/Zeiten in der Vergangenheit angegeben werden können (momentan nur Zukunft möglich)
