### ISSUE TITLE
Planung Orte?

### ISSUE THREAD

**Issue by Wurzelkoch** [irenenirgendwo/urantransporte#34]
Ich wollte mich mal mit der Ortsabfrage (Welche Transporte gehen vor meiner Haustür lang?) beschäftigen. 
Dazu wüsste ich gern, wie einige Beziehungen in der Datenbank gedacht sind:
`Transportabschnitt.start/end_ort` -> Soll das auf eine Anlage oder einen Ort verweisen?
Ist `Umschlag.terminal` eine Anlage?

Mein Vorschlag wäre ja, als Umschlagsterminal ein Anlage zu verwenden, die als Start-und Endpunkt von Transporten ebenso wie Transportabschnitten wieder auftaucht. Das Anlagen-Konstrukt hat ja eine Ortsangabe, die mensch dann über z.B. [Geokit](http://www.rubydoc.info/gems/geokit/1.9.0/frames) mit der Abfrageeingabe vergleichen kann.
Dann hätte man zumindestens die Umschlagsorte abgedeckt.
Dann könnte ich mir vorstellen, zwischen Transportabschnitten und Orten eine n:m-Beziehung als Routenverlauf zu implementieren, um auch Durchfahrtsorte abzudecken.

Was sagt ihr dazu?

**Comment by irenenirgendwo** [comment]
Was mir noch einfällt: Wenn bei der Anlage ein Ort geändert wird, soll der bei verknüpften Transporten bzw. Transportabschnitten auch geändert werden? 
Ganz schön viel Aufwand mit diesen Orten...

**Comment by irenenirgendwo** [comment]
Da hier schon einiges umgesetzt ist und ganz schon unübersichtlich wird, habe ich zwei neue Issues mit den offenen Punkten zu Orten angelegt, #51 und #52.
