### ISSUE TITLE
Produktions-Datenbank auf MySQL

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#39]
Für das Deployment wäre es gut, die Produktionsdatenbank auf MySQL umzustellen. Auf dem netzguerilla-Server läuft MySQL und für größere Datenmengen ist SQLlite eh nicht gedacht.

**Comment by irenenirgendwo** [comment]
So ich habe es installiert bekommen bei mir. Wenn es bei euch Probleme gibt: Das Nachinstallieren eines sql-Pakets mit "sudo apt-get install libmysqlclient-dev " hat es schließlich gebracht. Dann habe ich noch in mysql eine Datenbank mit Namen uran angelegt und einen Benutzer mit Namen und Passwort wie im Config-File und allen Rechten auf die Datenbank. Wenn ich die neue Datenbank als development-DB setze, funktioniert auch der Start, aber irgendwie noch nicht das seed, weiß nicht warum.

**Comment by KTim21** [comment]
bei mir war es genauso. Das Paket musste ich nachinstallieren und die seeds funktionieren auch nicht.

**Comment by KTim21** [comment]
Und ich kriege die seeds auch gerade nicht hin.... :/

**Comment by KTim21** [comment]
Es scheint nicht an mysql zu liegen, sondern die seeds funktionieren gerade generell nicht.

**Comment by KTim21** [comment]
bei mir funktioniert es jetzt
