### ISSUE TITLE
Ort ändern

### ISSUE THREAD

**Issue by Wurzelkoch** [irenenirgendwo/urantransporte#40]
Wird in einer Anlage mit eingetragenem Ort der Ortsname (egal ob mit oder ohne PLZ) geändert, wird aktuell nur der Name bzw. Name und PLZ des verknüpften Ortsdatensatzes geändert. Die Koordinaten bleiben gleich, passen also nicht mehr zum Namen.
Um Chaos bei mehreren Anlagen im Ort zu vermeiden, von denen evtl. nur eine verschoben werden soll, wäre es sinnvoll, einen neuen Ort anzulegen, bzw. neu nach vorhandenen Orten zu suchen wie wenn zum ersten Mal ein Ort eingegeben wird. Also quasi die alte Verknüpfung verwerfen und neu aufbauen.

**Comment by irenenirgendwo** [comment]
Gerne nochmal prüfen, ob das jetzt so korrekt arbeitet.

**Comment by Wurzelkoch** [comment]
Beim schnellen Überblick scheint nein, für genauere Problemanalysen hab ich leider im Moment und wahrscheinlich bis nächste Woche keine Zeit. Ich nehm mir die Zeit, sobald ich die Gelegenheit habe.

**Comment by Wurzelkoch** [comment]
OK, doch, jetzt tritt das Problem so nicht mehr auf. Dafür andere, aber für die gibt es neue Issues.
