### ISSUE TITLE
Orte bei Transportabschnitten

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#41]
Ich habe überlegt, die Ortseingabe bei Transporabschnitten so zu machen, dass ein Ortseingabeformular da ist und jeweils bei Start und Ziel ein Button "Ort auf Ortseingabeformular" zuordnen statt dem jetzigen Textfeld für den Ort. Was meint ihr? 
Zwei Ortseingabeformulare sähen doof aus, wären auch nicht so einfach einbindbar wegen gleichen Parametern.

**Comment by KTim21** [comment]
spontane Idee: das ganze als modal, dann wäre es für mich zumindest weniger verwirrend

**Comment by irenenirgendwo** [comment]
Klingt gut, muss ich mal schauen, ob ich das hinbekomme.
