### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#47]
Deployment-Variante über nginx und uswgi ausprobieren.
Mit welchen Parametern muss uswgi gestartet werden?
Beispiel: uwsgi --plugins http,rack --http :8081 --http-modifier1 7 --rack config.ru 
http://uwsgi-docs.readthedocs.org/en/latest/Ruby.html

**Comment by irenenirgendwo** [comment]
Läuft jetzt. Readme-Datei ergänze ich noch.

**Comment by irenenirgendwo** [comment]
In der production-Umgebung funktioniert das Layout noch nicht, irgendwie wird das bootstrap nicht eingebunden.

**Comment by KTim21** [comment]
Bei mir funktioniert das Layout auch in der production-Umgebung.

Wird nur bootstrap nicht eingebunden oder gibt die ganze CSS-Datei einen 404-Error?

**Comment by irenenirgendwo** [comment]
Seltsam. Ich bekomme keinen error (nicht im production.log) sondern einfach nur eine Seite ohne Layout mit Text und Links und so drauf, aber ohne Bilder, Anordnung usw.

**Comment by KTim21** [comment]
Ich musste das gem 'rails_serve_static_assets' installieren, um das Layout zu kriegen. Allerdings sollte das nur beim lokalen Aufruf über webrick nötig sein und auf einem echten Server einfach so funktionieren. Da soll das gem sogar nicht installiert sein, weswegen ich das nicht commited habe.

Relevante Frage wäre jetzt, ob überhaupt irgendwas an CSS eingebunden wird oder ob nur der bootstrap-Teil fehlt. Bei mir war zu Anfang der Fehler, dass ich, wenn ich in der Quelltext-Ansicht auf die CSS-Datei geklickt habe, einne 404-Fehler bekam.

**Comment by irenenirgendwo** [comment]
Ich habe auch den 404-Fehler (auch nach Installation des gem). Obwohl ich den rake assets:precompile Befehl ausgeführt habe.

Vielleicht probiere ich mal die Tage einspielen auf dem Server aus und sehe was rauskommt.

**Comment by KTim21** [comment]
Dann sollte es auf dem Server (mit vorher rake assets:precompile) funktionieren. Lokal solltest du es mit dem gem  'rails_serve_static_assets' hinkriegen.

**Comment by irenenirgendwo** [comment]
Die Produktion ist jetzt umgestellt auf die production-Umgebung. Wenn ich das richtig sehe, gibt es noch kleinere Fehler, z.B. bei der Anzeige der Marker in den Grafiken. Hast du da Ideen, woran das liegen könnte?

**Comment by irenenirgendwo** [comment]
Irgendwie scheint mir das so, als werden die bootstrap-Bilder nicht geladen. Wo liegen die denn bzw. woher werden die in der development-Umgebung genommen?

**Comment by KTim21** [comment]
Bei mir funktioniert alles.
