### ISSUE TITLE
Transportabschnitt-Orte-Eingabe

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#48]
Wie soll das bei der Transportabschnitt-Eingabe mit den Ortseingaben laufen? 
a) Über Modal-Link zur Ortseingabe, da öffnet sich dann Karte usw. und der Ort wird entsprechend zugewiesen.
b) Über zwei Ortseingabe-Fenster, eins für Startort und eins für Zielort, die schon im Formular sind.
Ich habe gerade mal beide Möglichkeiten zur Ansicht eingebaut (a bei Startanlage und b bei Zielanlage), bei beidem gibt es Realisierungsschwierigkeiten, aber bekomme ich schon irgendwie hin, wir müssten uns nur entscheiden.

Erhalten bleiben soll natürlich die Möglichkeit, die Startanlage direkt als Startort und die Zielanlage als Zielort einzutragen (dabei ist momentan noch ein Bug, aber den behebe ich noch - bei Orten mit gleichem Namen wird nicht unbedingt der der Anlage ausgewählt).

**Comment by irenenirgendwo** [comment]
Ich glaube, ich fände es mit Modallinks einfacher zu implementieren. Ist das für euch ok?

**Comment by irenenirgendwo** [comment]
Damit ist der Bug behoben, es bleibt zu tun, das Javascript-Template bei der Ortseingabe aus dem Modal-Fenster korrekt hinzubekommen, den Ort also zu speichern (create) und im Formular anschließend zuzuweisen (per Javascript).

**Comment by irenenirgendwo** [comment]
Müsste jetzt so funktionieren, vielleicht könnt ihr auch nochmal testen?

**Comment by KTim21** [comment]
Beim Endort wird gar keine Karte angzeigt. Liegt vermutlich dran, dass es das div mit id="map" zweimal gibt.

**Comment by irenenirgendwo** [comment]
So ich hoffe, ich habe die Formulare jetzt korrekt auseinander sortiert (ganz schön nervig mit den Orten...)
