### ISSUE TITLE
Mengeangaben

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#49]
Getrennte Spalten für Brutto und Nettoangaben bei den Transporten anlegen. Beim Einlesen muss dann ausgewählt werden, ob Brutto oder Nettoangabe. Dann kann potentiell noch das Versandstück als Extra-Tabelle herausgezogen werden mit Angaben zu Gewicht etc um mögliche Umrechnungen zu machen. Die Vorbereitung mit den getrennten Spalten würde ich aber jetzt schon machen wollen.

**Comment by KTim21** [comment]
+1
