### ISSUE TITLE
Kalender-Darstellung

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#5]
Gibt es ein tolles Tool, um sich Transportlisten in einem Kalender darstellen zu lassen?
In etwa wie hier:  http://www.anti-atom-aktuell.de/aktuelles/20140219-urenco-ticket-2013.html

**Comment by KTim21** [comment]
Welche Informationen müssen *unbedingt* schon auf den ersten Blick sichtbar sein? Für welche reicht ein Mouseover?

**Comment by irenenirgendwo** [comment]
Also auf jeden Fall die Transportdauer (durch durchgehenden Strich mit markierten Umschlägen o.ä.) und dann am liebsten noch entweder Start/Ziel oder Stoff, Rest würde mir bei Mausover reichen.

**Comment by KTim21** [comment]
Das ganze scheint ein gewaltiger Aufwand zu werden. Insbesondere der durchgehende Strich. Ich sehe gerade zwei Möglichkeiten:
* Wir verzichten auf durchgehende Darstellung von Transportabschnitten, so wie es jetzt im Prinzip schon ist.
* Wir verzichten auf die Jahresansicht und bauen mit fertigen gems eine Monatsansicht. Dann ist alles kein Problem.

**Comment by irenenirgendwo** [comment]
Hm, 
Mein Problem mit den Monatsansichten ist, dass den richtigen Überblick und Regelmäßigkeiten habe ich meist erst mit Jahresansicht sehen können. 
Trotzdem wären natürlich auch schöne Monatsansichten toll und vielleicht brauche ja tatsächlich nur ich komische Jahresansichten

Wie wäre es, wenn wir den bisherigen Code auf jeden Fall im Projekt lassen und erst mal zusätzlich die Monatsansicht bauen mit fertigen gems? Das andere können wir dann zu gegebener Zeit ja erst mal verstecken und vielleicht später nochmal dran rumbasteln.

**Comment by KTim21** [comment]
Finde ich gut. Die Code wollte ich auf jeden Fall auch drin lassen und später evtl. de Jahresansicht fertg machen.

**Comment by KTim21** [comment]
Ist jetzt doch eine selbst gebaute Jahresansicht geworden. Noch nicht perfekt, aber brauchbar.
