### ISSUE TITLE
Orte löschen und zusammenführen

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#51]
Wegen der Übersichtlichkeit als neues Issue zur Ortsbereinigung:
- [x] Die Möglichkeit, die Ortsspeicherungen zu bereinigen, d.h. alle nirgendwo verwendeten Orte löschen (Button in Ortsübersicht)
- [x] Ähnliche Orte zusammen führen, z.B. einen Ort auswählen, dort Orte mit Koordinaten im Umkreis (oder alternativ ähnlichem Namen) auf Karte anzeigen und auswählen können, welche zu dem jetzigen Ort zusammen geführt werden sollen. Dabei müssten alle Referenzierungen auf den Ort upgedatet werden (also in Anlagen, Beobachtungen, Transportabschnitten, ...)
- [ ] evtl. eine Ortsbeschreibung hinzufügen? Das würde mehrere Orte in einer Stadt sinnvoll werden lassen, was ja z.B. bei Hamburg durchaus der Fall wäre.
- [x] Bei Anlagenupdate mit Ortsänderung soll der Ort auch bei der Anlage zugeordneten Transporten und entsprechenden Transportabschnitten geändert werden?

Wahrscheinlich wäre es die einfachere Lösung gewesen, jeweils die Koordinaten mitzuspeichern, aber na gut, es funktioniert dann hoffentlich...

**Comment by irenenirgendwo** [comment]
Die Ortsbeschreibung sollte vielleicht besser im Namen ergänzt werden (z.B. Name: Hamburg Süd-West-Terminal, dann passt das besser mit der Eindeutigkeit da). 

Aus irgendeinem Grund funktioniert das mit dem Zusammen führen der Orte nur in zwei Schritten: Aber beim zweiten Klick hat er dann alles übernommen und kann den alten Ort auch löschen. Ich weiß nicht woran das liegt. Aber immerhin tut es.

Wie ist das mit den Anlagenupdates und verbundenen Transportabschnitten?

**Comment by KTim21** [comment]
keine Ortsbeschreibung
