### ISSUE TITLE
Anmelden mit Benutzer*innen-namen

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#67]
Ich fände ja sinnvoll, wenn es auch möglich wäre, sich auch mit dem Benutzer*innen-Namen anzumelden, wozu gibt mensch den sich sonst?

**Comment by KTim21** [comment]
Zumindest bei mir geht das schon... Wenn es bei dir nicht geht, muss da irgendein Fehler sein.

**Comment by irenenirgendwo** [comment]
Bei mir funktioniert es auch.

**Comment by irenenirgendwo** [comment]
Klappt nicht, wenn die Benutzer*innen-Namen Großbuchstaben enthalten, kann das sein?

**Comment by Wurzelkoch** [comment]
Bei mir funktioniert es case-insensitive in jedem Fall.
