### ISSUE TITLE
Gefahrensymbole in Beobachtungsfomular

### ISSUE THREAD

**Issue by KTim21** [irenenirgendwo/urantransporte#69]
Bei den Gefahrensymbolen die Radioaktivitätsklassen unterscheiden? Zumindest Klasse I (weißer Hintegrund) ist gegenüber Klasse II/III (gelber Hintergrund) leicht unterscheidbar.

https://de.wikipedia.org/wiki/Gefahrgutklasse#Klasse_7_-_Radioaktive_Stoffe

**Comment by irenenirgendwo** [comment]
Keine Ahnung, bin ich unschlüssig. Soll ja auch nicht zu kompliziert werden.

**Comment by KTim21** [comment]
Ich denke, dass es zu kompliziert wird. Bei Bedarf kann es ja immer noch in der weiteren Beschreibung angegeben werden.
