### ISSUE TITLE
Ausloggen unabsichtlich

### ISSUE THREAD

**Issue by irenenirgendwo** [irenenirgendwo/urantransporte#75]
Beim Einlesen der csv-Dateien und danach auf den Link "Transporte ansehen" werde ich immer ausgeloggt ohne dass ich das will.

**Comment by irenenirgendwo** [comment]
Kannst du dir das erklären?

**Comment by KTim21** [comment]
Ich hab bisher nur mal kurz reingeguckt und hab noch keine Idee. Ich gucke aber nochmal genauer, ob ich irgendwas finde.

**Comment by KTim21** [comment]
Schuld war ein `session.clear`.
Ich habe das jetzt erstmal auskommentiert. Wenn einige session-Variablen unbedingt gelöscht werden müssen, müssten die einzeln gelöscht werden.
